### ISSUE TITLE
non-flashed/non-logged messages

### ISSUE THREAD

**Issue by sliptonic** [JohnAD/fondum#44]
process_form must return a message but there are times that it is undesirable to show a the message or log the event.

The flash can be suppressed with 
return msg.success("nothing to say", level=0)
but I think this level still implies the event will be logged.  There should be a level where nothing is done.

**Comment by JohnAD** [comment]
The following suppresses the display:

`msg.success("the message", display_level=msg.DISP_NONE)`

And, by default, this also would suppress the logger, since the default logging level is `logging.WARNING` and `msg.success` defaults to the `logging.DEBUG` level. To suppress even when debugging:

`msg.success("the message", display_level=msg.DISP_NONE, log_level=0)`

Also, `level=n` is now deprecated because it is vague, but using it will not generate an error.
